@echo off

SET txFile=../Classes/Speech/tx.h
SET speechdbFile=speechdb.txt

:: remove content of file
break > %txFile%

:: ##### make tx.h file #####

echo ^/^/ ^#^#^#^#^# Header file of tx generated by script ^#^#^#^#^# >> %txFile%
echo. >> %txFile%
echo #pragma once >> %txFile%
echo. >> %txFile%
echo #include ^<string^> >> %txFile%
echo. >> %txFile%
echo class tx >> %txFile%
echo { >> %txFile%
echo public: >> %txFile%
echo. >> %txFile%

for /F "usebackq tokens=1-2 delims=|" %%a in (%speechdbFile%) do (
     echo 	static LPCWSTR %%a^(^)^{ return L"%%b"; ^}; >> %txFile%
)

echo. >> %txFile%
echo }; >> %txFile%






