// ##### Header file of tx generated by script ##### 
 
#pragma once 
 
#include <string> 
 
class tx 
{ 
public: 
 
	static std::string welcome(){ return "Welcome!"; }; 
	static std::string introduction(){ return "Hi, I am Salli, a virtual assistant based on artificial intelligence."; }; 
	static std::string thank_you(){ return "Thank you!"; }; 
	static std::string no_problem(){ return "No problem!"; }; 
	static std::string your_welcome(){ return "Your welcome!"; }; 
	static std::string my_pleasure(){ return "My pleasure!"; }; 
	static std::string ok(){ return "Ok!"; }; 
	static std::string its_ok(){ return "It's ok!"; }; 
	static std::string allright(){ return "Allright!"; }; 
	static std::string yes(){ return "Yes!"; }; 
	static std::string no(){ return "No!"; }; 
	static std::string how_are_you(){ return "How are you?"; }; 
	static std::string who_are_you(){ return "Who are you?"; }; 
	static std::string say_again(){ return "Say again please!"; }; 
	static std::string something_went_wrong(){ return "Something went wrong!"; }; 
	static std::string main_program_start(){ return "Smarthome project has launched!"; }; 
	static std::string main_program_stop(){ return "Smarthome project has stopped!"; }; 
	static std::string main_program_run(){ return "Smarthome project is running!"; }; 
 
}; 
